/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as StudioRouteRouteImport } from './routes/_studio/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioDashboardRouteImport } from './routes/_studio/dashboard'
import { Route as StudioCategoriesRouteImport } from './routes/_studio/categories'
import { Route as StudioProductsRouteRouteImport } from './routes/_studio/products/route'
import { Route as StudioProductsIndexRouteImport } from './routes/_studio/products/index'
import { Route as StudioProductsNewRouteImport } from './routes/_studio/products/new'
import { Route as StudioProductsIdRouteImport } from './routes/_studio/products/$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDashboardRoute = StudioDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioCategoriesRoute = StudioCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioProductsRouteRoute = StudioProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioProductsIndexRoute = StudioProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioProductsRouteRoute,
} as any)
const StudioProductsNewRoute = StudioProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioProductsRouteRoute,
} as any)
const StudioProductsIdRoute = StudioProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/products': typeof StudioProductsRouteRouteWithChildren
  '/categories': typeof StudioCategoriesRoute
  '/dashboard': typeof StudioDashboardRoute
  '/products/$id': typeof StudioProductsIdRoute
  '/products/new': typeof StudioProductsNewRoute
  '/products/': typeof StudioProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/categories': typeof StudioCategoriesRoute
  '/dashboard': typeof StudioDashboardRoute
  '/products/$id': typeof StudioProductsIdRoute
  '/products/new': typeof StudioProductsNewRoute
  '/products': typeof StudioProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_studio': typeof StudioRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/_studio/products': typeof StudioProductsRouteRouteWithChildren
  '/_studio/categories': typeof StudioCategoriesRoute
  '/_studio/dashboard': typeof StudioDashboardRoute
  '/_studio/products/$id': typeof StudioProductsIdRoute
  '/_studio/products/new': typeof StudioProductsNewRoute
  '/_studio/products/': typeof StudioProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/products'
    | '/categories'
    | '/dashboard'
    | '/products/$id'
    | '/products/new'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/categories'
    | '/dashboard'
    | '/products/$id'
    | '/products/new'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_studio'
    | '/signin'
    | '/_studio/products'
    | '/_studio/categories'
    | '/_studio/dashboard'
    | '/_studio/products/$id'
    | '/_studio/products/new'
    | '/_studio/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/dashboard': {
      id: '/_studio/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StudioDashboardRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/_studio/categories': {
      id: '/_studio/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof StudioCategoriesRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/_studio/products': {
      id: '/_studio/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof StudioProductsRouteRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/_studio/products/': {
      id: '/_studio/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof StudioProductsIndexRouteImport
      parentRoute: typeof StudioProductsRouteRoute
    }
    '/_studio/products/new': {
      id: '/_studio/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof StudioProductsNewRouteImport
      parentRoute: typeof StudioProductsRouteRoute
    }
    '/_studio/products/$id': {
      id: '/_studio/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof StudioProductsIdRouteImport
      parentRoute: typeof StudioProductsRouteRoute
    }
  }
}

interface StudioProductsRouteRouteChildren {
  StudioProductsIdRoute: typeof StudioProductsIdRoute
  StudioProductsNewRoute: typeof StudioProductsNewRoute
  StudioProductsIndexRoute: typeof StudioProductsIndexRoute
}

const StudioProductsRouteRouteChildren: StudioProductsRouteRouteChildren = {
  StudioProductsIdRoute: StudioProductsIdRoute,
  StudioProductsNewRoute: StudioProductsNewRoute,
  StudioProductsIndexRoute: StudioProductsIndexRoute,
}

const StudioProductsRouteRouteWithChildren =
  StudioProductsRouteRoute._addFileChildren(StudioProductsRouteRouteChildren)

interface StudioRouteRouteChildren {
  StudioProductsRouteRoute: typeof StudioProductsRouteRouteWithChildren
  StudioCategoriesRoute: typeof StudioCategoriesRoute
  StudioDashboardRoute: typeof StudioDashboardRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioProductsRouteRoute: StudioProductsRouteRouteWithChildren,
  StudioCategoriesRoute: StudioCategoriesRoute,
  StudioDashboardRoute: StudioDashboardRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
